NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', lambda request: redirect('news/', permanent=False)),
    path('news/', include('news.urls')),

    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),

    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import Posts, SearchPost, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, AuthorsList
from .views import AuthorDetail, CategoryAdd, CategoryRemove


urlpatterns = [
    path('', Posts.as_view()),
    path('search', SearchPost.as_view()),
    path('<int:pk>/', PostDetailView.as_view(), name='post'),
    path('add/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('authors', AuthorsList.as_view()),
    path('authors/<int:pk>/', AuthorDetail.as_view()),
    path('subscribe/<int:pk>', CategoryAdd.as_view(), name='subscribe'),
    path('unsubscribe/<int:pk>', CategoryRemove.as_view(), name='unsubscribe'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    author_user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRate = 0
        pRate += postRat.get('postRating')

        commentRat = self.author_user.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.author_rating = pRate * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.author_user.username}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, null=True,
                                         related_name='subscription',
                                         verbose_name='Подписчики')

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    category_type = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    date_creation = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...'  # лучше исп форматирование для экономии памяти

    def __str__(self):
        return f'{self.title} | {self.author} | {self.post_category.all()} | {self.date_creation} | {self.preview()} | {self.rating}'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/news/{self.id}'


class PostCategory(models.Model):
    post_through = models.ForeignKey(Post, on_delete=models.CASCADE)
    category_through = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category_through}'


class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.comment_user} | {self.date_creation}/n{self.text}'

NewsPaper/news/forms.py
from django.forms import ModelForm
from .models import Post, Category
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'category_type', 'text',  'post_category']


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = []

NewsPaper/news/views.py
from django.shortcuts import render, reverse, redirect
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from django.core.paginator import Paginator
from .models import Author, Post, User, Category
from datetime import datetime
from .filters import PostFilter
from .forms import PostForm, CategoryForm  # импортируем нашу форму
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives, mail_admins, send_mail


class CategoryAdd(CreateView):
    template_name = 'subscribe.html'
    model = Category
    queryset = Post.objects.all()
    form_class = CategoryForm


    def post(self, request, *args, **kwargs):
        user = self.request.user
        id = self.kwargs.get('pk')
        Category.objects.get(pk=id).subscribers.add(user)
        return redirect('/')


class CategoryRemove(CreateView):
    template_name = 'unsubscribe.html'
    model = Category
    queryset = Category.objects.all()
    form_class = CategoryForm


    def post(self, request, *args, **kwargs):
        user = self.request.user
        id = self.kwargs.get('pk')
        Category.objects.get(pk=id).subscribers.remove(user)
        return redirect('/')


class AuthorsList(ListView):
    model = Author
    template_name = 'authors.html'
    context_object_name = 'authors'
    queryset = Author.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class AuthorDetail(DetailView):
    model = Author
    template_name = 'author.html'
    context_object_name = 'author'
    queryset = Author.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs.get('pk')
        user = self.request.user
        context['author'] = Author.objects.get(pk=id).author_user.all()
        return context


class Posts(ListView):
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    ordering = ['-date_creation']
    queryset = Post.objects.all()
    paginate_by = 3  # поставим постраничный вывод в один элемент

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()

        return context


# дженерик для получения деталей о товаре
class PostDetailView(DetailView):
    model = Post
    template_name = 'news/post.html'
    context_object_name = 'post'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs.get('pk')
        user = self.request.user
        context['post_categories'] = Post.objects.get(pk=id).post_category.all()
        context['user_categories'] = Category.objects.filter(subscribers=User.objects.get(username=str(user)))
        return context


class SearchPost(ListView):
    model = Post
    template_name = 'search.html'
    context_object_name = 'news'
    ordering = ['-date_creation']
    paginate_by = 10  # поставим постраничный вывод в один элемент

    def get_context_data(self, **kwargs):  # забираем отфильтрованные объекты переопределяя метод get_context_data
        # у наследуемого класса (привет, полиморфизм, мы скучали!!!)
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['categories'] = Category.objects.all()
        context['form'] = PostForm()
        return context


# дженерик для создания объекта.
class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'news/post_create.html'
    form_class = PostForm
    permission_required = ('news.add_post')


# дженерик для редактирования объекта
class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'news/post_edit.html'
    form_class = PostForm
    permission_required = ('news.change_post')

# метод get_object мы используем вместо queryset, чтобы получить информацию об объекте, который мы собираемся
    # редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


# дженерик для удаления товара
class PostDeleteView(DeleteView):
    model = Post
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = '/news/'

NewsPaper/templates/author.html
{%extends 'flatpages/default.html' %}

{% block title %}
Author
{% endblock title %}


{% block content %}
    <h1>Имя автора</h1>
    {{ author_user }}

{% endblock content %}

NewsPaper/templates/authors.html
{%extends 'flatpages/default.html' %}

{% block title %}
Authors
{% endblock title %}


{% block content %}
    <h1>Авторы</h1>
<p style="text-align: left;">
{% for author in authors %}
    {{ author.author_user }}<br>
{% endfor %}</p>

{% endblock content %}

NewsPaper/templates/base.html
{% extends 'flatpages/default.html' %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

NewsPaper/templates/main.html
{% extends 'flatpages/default.html' %}

<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %} News {% endblock title %}

{% block content %}

<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href="/accounts/login/">Войти</a> </button>
<button> <a href="/accounts/logout/">Выйти</a> </button>

{% if is_not_author %}
<button> <a href="/sign/upgrade/"> Стать автором </a> </button>
{% endif %}

<p></p>

<a href="search" class="btn btn-secondary" style="margin-bottom: 3%">Поиск</a>
<a href="{% url 'post_create' %}" class="btn btn-secondary" style="margin-bottom: 3%">Добавить новость</a>

{% autoescape off %}

    <p></p>
    <p></p>
    <h3 style="text-align: left;"><strong>Все новости: ({{ news|length }})</strong></h3>
    <hr>

    {% if news %}
        {% for post in news %}
            <p style="text-align: left;">
            <a href="{% url 'post' post.id %}"><strong>{{ post.title|censor|title }}</strong></a>
            <a href="{% url 'post_update' post.id %}">Редактировать</a>
            <a href="{% url 'post_delete' post.id %}">Удалить</a>
            </p>
            <p style="text-align: left;"><strong>{{ post.get_category_type_display|title }},
            </strong>дата публикации: {{ post.date_creation|date:'d.m.Y' }}
<strong>Категория:</strong> {% for post_category in post.post_category.all %}
    {{ post_category.name }} |
    {% endfor %}</p>

            <p style="text-align: left;">{{ post.text|truncatechars:50|censor }}</p>
<br>

        {% endfor %}
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

{% endautoescape %}

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %} News {% endblock title %}

{% block content %}

    <p></p>
    <form method="GET">
        {{ filter.form }}
    <input type="submit" value="Найти">
    </form>

    {% autoescape off %}
    <p></p>
    <p></p>
    <h3 style="text-align: left;"><strong>Все новости: ({{ news|length }})</strong></h3>
    <hr>
    {% if news %}
        {% for post in filter.qs %}
            <h4 style="text-align: left;"><strong>{{ post.title|censor|title }}</strong></h4>
            <p style="text-align: left;"><strong>{{ post.get_category_type_display|title }},&nbsp;
            </strong>дата публикации: {{ post.date_creation|date:'d.m.Y' }}
            <strong>Категория:</strong> {% for post_category in post.post_category.all %}
                {{ post_category.name }} |
                {% endfor %}</p>
            <p style="text-align: left;">{{ post.text|truncatechars:50|censor }}</p>
        {% endfor %}
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
    {% endautoescape %}


    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
 
{% block title %} Post list {% endblock title %}
 
{% block content %}
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
        <h5>Уверены, что хотите подписаться на выбранную категорию? </h5>
    <input type="submit" value="Подписаться">
</form>
{% endblock content %}

NewsPaper/templates/unsubscribe.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
 
{% block title %} Post list {% endblock title %}
 
{% block content %}
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
        <h5>Уверены, что хотите отписаться от выбранной категории? </h5>
    <input type="submit" value="Отписаться">
</form>
{% endblock content %}